In [11]:
#Import NumPy
import numpy as np

In [12]:
#first numpy arrary
first_numpy_array = np.array([1,2,3,4,5,6])

In [13]:
#print first array
print (first_numpy_array)

[1 2 3 4 5 6]


In [14]:
#array with zeros
array_with_zero = np.zeros((3,3))
array_with_zero

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [15]:
#array with ones
array_with_ones = np.ones((3,3))
array_with_ones

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [16]:
#array with empty
Array_with_empty = np.empty((2,2))
Array_with_empty

array([[8.09273937e+305, 4.99425854e-307],
       [1.33360382e+241, 4.26139195e-310]])

In [19]:
#np array with arrange method
np_arange = np.arange(12)

#print arrange
print(np_arange)

[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [23]:
#reshape method to create or change array
np_reshape = np_arange.reshape(6,2)
np_reshape

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11]])